import { useState } from 'react'
import { sendRequest } from '../helpers'
import Head from 'next/head'
import Card from '../components/Card'
import styles from '../styles/Banner.module.css'
import BannerListHeader from '../components/BannerListHeader'
import BannerList from '../components/BannerList'

export default function Banners({ request }) {
  console.log(request,"request")
  const [banners, setBanners] = useState([...request])

  const onDeleteHandler = async(id)=> {
    try {
      const requestConfig = {
        method:'DELETE',
        url: `https://peaksoftadmin-default-rtdb.firebaseio.com/banners/${id}.json`,
      }
      const response= await sendRequest(requestConfig)
      console.log(response)
      const newBanners = banners.filter((item) => item.id !== id)
      setBanners(newBanners)
    } catch (error) {
      console.log(error.message)
    }
  } 

  const onEditHandler = async(bannerId)=> {
    console.log(bannerId)
  }

  const onCheckedRequestHandler =async({id, checked})=> {
    console.log(id, checked, 'checked')
    const requestConfig = {
      method:'PATCH',
      url: `https://peaksoftadmin-default-rtdb.firebaseio.com/banners/${id}.json`,
      body: {checked}
    }
    const response = await sendRequest(requestConfig)
    console.log(response)
  }

  const onSwitchedRequestHandler = async({id, view})=> {
    console.log(id, view, 'view')
    const requestConfig = {
      method:'PATCH',
      url: `https://peaksoftadmin-default-rtdb.firebaseio.com/banners/${id}.json`,
      body: {view}
    }
    const response = await sendRequest(requestConfig)
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Banner</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.bannerTitleContainer}>
        <h1 >Баннер</h1>
        <button className={styles.buttonCreateBanner}>Создать баннер</button>
      </div>
      <Card className={styles.banner}>
        <BannerListHeader/>
        <BannerList 
        onDeleteHandler={onDeleteHandler} 
        onEditHandler={onEditHandler}
        onCheckedRequestHandler={onCheckedRequestHandler}
        onSwitchedRequestHandler={onSwitchedRequestHandler}
        banners={banners}
        />
      </Card>
    </div>
  )
}

export async function getStaticProps() {
  const consfigRequest = {
    url: 'https://peaksoftadmin-default-rtdb.firebaseio.com/banners.json'
  }
  const request = await sendRequest(consfigRequest)
  return {
    props: {
      request
    },
  }
}


